# Generated by Django 4.1.7 on 2023-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_customuser_type_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hotels',
        ),
        migrations.AddField(
            model_name='hotel',
            name='services',
            field=models.ManyToManyField(to='hotels.service'),
        ),
    ]
