# Generated by Django 4.1.7 on 2023-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_customuser_user_type_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('guest', 'guest'), ('owner', 'owner'), ('admin', 'admin')], default='guest', max_length=10),
        ),
    ]
