# Generated by Django 4.1.7 on 2023-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'guest'), (2, 'owner'), (3, 'admin')], default='guest', max_length=10),
        ),
    ]
