# Generated by Django 4.1.7 on 2023-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'guest'), (2, 'owner'), (3, 'admin')], default=3),
        ),
    ]
